### ISSUE TITLE
Update to  Spring Platform

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#177]
Lightadmin should be updated, thus it works with `spring platform 1.1.2` and thus with the latest spring-boot version (see la-team/lightadmin-springboot#5)

- [x] Update code to work with Java 8, see #179 
- [x] Update to spring-data-rest-2.3.0 (and others) (was provided by a user, see PR #186)
- [ ] Update to use maven dependency management (with same version numbers, and still whilst using properties), see #176

Most possibly, smaller problems will come up here (there is a possibility that code must be ported to earlier spring-data-rest, in order to ensure compatibility with spring-boot):
 
- [ ] Update to use the spring-platform-bom (or other bom's) for version numbers, see #185
  - [ ] Create branch, update to `spring-platform-1.1.2`
  - [ ] Create branch, update to `spring-platform-2.0.0` (based on branch `spring-data-rest-2.3.0`)

At this point, the admin should be usable with no version-problems across spring (due to the use of spring-platform).

This should be trivial:

- [ ] Adjust spring-boot example

**Comment by lazaridis-com** [comment]
moved to lazaridis-com/light-admin#2
